version: "3"

services:
  db:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./.docker/data:/data

  app:
    image: thuongtruong1009/short1url
    build: app
    ports:
      - "3000:3000"
    depends_on:
      - db