version: "3"

services:
  redis:
    image: redis:7.0-alpine
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./.docker/data:/data
    networks:
      - app-network
    restart: always

  client:
    # image: thuongtruong1009/short1url-client
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env
    ports:
      - "3000:3000"
    environment:
      - NUXT_PUBLIC_API_BASE=http://localhost:81/s
    volumes:
      - ./client:/app/client
    networks:
      - app-network
    restart: always

  api:
    # image: thuongtruong1009/short1url-api
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./api/.env
    ports:
      - "8080:8080"
    environment:
      - DOMAIN_RETURN=localhost:81/s
    depends_on:
      - redis
    networks:
      - app-network
    volumes:
      - ./api:/app/api
    restart: always

  nginx:
    image: nginx:1.24-alpine
    container_name: nginx
    ports:
      - "81:80"
    volumes:
      - ./:/usr/share/nginx/html
      - ./:/var/www
      - ./nginx:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - client
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
