version: "3"

services:
  db:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./.docker/data:/data
    networks:
      - app-network
    restart: always

  commander:
    container_name: commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:db:6379
    ports:
    - "6380:8081"

  client:
    container_name: client
    build: ./client
    env_file:
      - ./client/.env
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: always

  app:
    container_name: app
    build: ./app
    env_file:
      - ./app/.env
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
    restart: always

  nginx:
    image: nginx:1.24-alpine
    container_name: nginx
    ports:
      - "81:80"
    volumes:
      - ~/nginx:/var/log/nginx
      - ~/nginx/default.conf:/etc/nginx/conf.d
    depends_on:
      - client
      - app
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge