version: "3"

services:
  db:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./.docker/data:/data
    restart: always

  commander:
    container_name: commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:db:6379
    ports:
    - "6380:8081"

  client:
    container_name: client
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      # - ./client:/client
      - /client/node_modules
    command: "npm run dev"
    networks:
      - app-network
    restart: always

  app:
    container_name: app
    build: ./app
    ports:
      - "8080:8080"
    # volumes:
    #   - ./app:/app
    depends_on:
      - db
    networks:
      - app-network
    restart: always

  nginx:
    image: nginx:1.24-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx:/var/log/nginx
    depends_on:
      - client
      - app
    networks:
      - app-network


networks:
  app-network: