version: "3"

services:
  db:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./.docker/data:/data
    networks:
      - app-network
    restart: always

  commander:
    container_name: commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:db:6379
    ports:
      - "6380:8081"

  client:
    container_name: client
    build: ./client
    env_file:
      - ./client/.env
    ports:
      - "3000:3000"
    environment:
      - SERVER_URL=http://localhost:81/s
    volumes:
      - ./client:/client
      - /client/node_modules
    networks:
      - app-network
    restart: always

  api:
    container_name: app
    build: ./app
    env_file:
      - ./app/.env
    ports:
      - "8080:8080"
    environment:
      - DOMAIN=localhost:81/s
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./app:/app/app
    restart: always

  nginx:
    image: nginx:1.24-alpine
    container_name: nginx
    ports:
      - "81:80"
    volumes:
      - ./:/usr/share/nginx/html
      - ./:/var/www
      - ./nginx:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      # - client
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
