version: 2.1

jobs:
  build:
    working_directory: /go/src/github.com/thuongtruong1009/short1url
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - run: cd api
      - run:
          name: Install dependencies
          command: go mod tidy
      - run: go test -v ./...
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports
      - run:
          name: Build the application
          command: go build -o main

workflows:
  build-deploy:
    jobs:
      - build
