version: 2.1

jobs:
  build:
    working_directory: /go/src/github.com/thuongtruong1009/short1url
    docker:
      - image: cimg/go:1.20
    steps:
      - checkout
      - run: cd api && go mod tidy && go test -v ./...
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports
      - run:
          name: Build the application
          command: cd api && go build -o main

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
