FROM golang:1.20-alpine as development

RUN mkdir /app

ADD go.mod go.sum /app/

WORKDIR /app

RUN go mod tidy

COPY . /app

RUN go build -o main main.go

FROM golang:1.20-alpine as production

COPY . /app

COPY --from=development /app/main.go /app/

WORKDIR /app

EXPOSE 8081

CMD ["go", "run", "./main.go"]