name: Build and push

on:
  push:
    branches:
      - main
    paths-ignore:
      - "!.github/**"
      - "!app/**"
      - "!client/**"
      - "!nginx/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # api
      - name: Build and push api image
        uses: docker/build-push-action@v3
        with:
          context: ./app
          push: true
          tags: ghcr.io/${{ github.repository }}/api:latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}

      # client
      - name: Build and push client image
        uses: docker/build-push-action@v3
        with:
          context: ./client
          push: true
          tags: ghcr.io/${{ github.repository }}/client:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.repository.pushed_at }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
