name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "!.github/**"
      - "!app/**"
      - "!client/**"
      - "!nginx/**"
  pull_request:
    paths-ignore:
      - "!.github/**"
      - "!app/**"
      - "!client/**"
      - "!nginx/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          cache-dependency-path: api/go.sum

      - name: Install dependencies
        run: |
          cd api
          go get .
          go mod download

      - name: Build and test
        run: |
          cd api
          go build -v ./...
          go test -v ./...
          go test -json > test.json
